#!/bin/bash
i3_folder="$HOME/.config/i3"
i3_config_file="$i3_folder/config"
i3_config_dir="$i3_folder/config.d"

if [ -d "$i3_config_dir" ]
then

  echo "#### DO NOT EDIT THIS FILE, IT IS GENERATED." > "$i3_config_file"
  echo "#### EDIT THE FILES HERE: $i3_folder/config.d/**/*" >> "$i3_config_file"
  
	cat "$i3_config_dir/vars" >> "$i3_config_file"
	cat "$i3_config_dir/base" >> "$i3_config_file"
	cat "$i3_config_dir/startup" >> "$i3_config_file"
	cat "$i3_config_dir/shortcuts" >> "$i3_config_file"
	cat "$i3_config_dir/workspaces" >> "$i3_config_file"
	cat "$i3_config_dir/windows" >> "$i3_config_file"
fi